### ISSUE TITLE
Group 4 Tutorial Review

### ISSUE THREAD

**Issue by cck011** [Bucknell-Biol364/Project_1_Group_4_2024#1]
https://github.com/Bucknell-Biol364/Project_1_Group_4_2024/blob/f2cae22f0124d1788d0ec09d639e444452952998/Project1v1(use_for_review).Rmd#L2

Cleaner and Clearer file management would benefit both continued effort on this tutorial and navigating it later on. 

The ASCII penguin is very cute

Solid concept, very early audience, feels appropriately chosen

Nice choice with variable conversion

The breakdown of simple functions is appropriate to audience, especially where it is incorporated relative to the other preceding instructions

The transition from not knowing what an RMD is to mutating does seem a bit fast, I wonder if maybe there might be a more gradual transition but then again your presentation was constrained to a pretty narrow timeframe so that might just be it and while the file looks rather short, it might take more time to actually run through it. One way or another, it might be worth looking into, maybe even adding something about the syntax.

Learning what an RMD is all the way to performing Statistical Analysis is very impressive. 

Touch on a very similar topic and goals to our tutorial.

Your tutorial seems more explanatory rather than interactive, I wonder if a larger interactive element could be easier and more entertaining. 

Viridis is a cool package inclusion!

**Comment by tpymz** [comment]
Thank you for the comments!
