### ISSUE TITLE
Peer Feedback #1

### ISSUE THREAD

**Issue by sweta-aryal** [Bucknell-Biol364/Project_1_Group_4_2024#2]
https://github.com/Bucknell-Biol364/Project_1_Group_4_2024/blob/f2cae22f0124d1788d0ec09d639e444452952998/Project1v1(use_for_review).Rmd#L19

1. Excellent objectives for a person to get started with R as it incorporates almost all the basic things one might require to be able to do some basic analysis of a dataset.
2. I think you should have mentioned downloading the dataset file in the same directory as the project tutorial file, because I had an error to run that code without extracting the dataset. And, without being able it to run the read.csv code without further instructions, one will not be able to follow through the whole turorial. I also couldn't find the dataset file in this repo. (I might have missed it, but it would be great if you guys work on this part).
3.  In objective 3 (Manipulating data), you used the "group_by" function and mentioned why it's used, but in the same code, you have used the pipe operator |> sign which hadn't been used before. It would be better to provide information about what it is and how it works. In the same code, the reason for choosing meanMass?
4. What does the dim function do and when should we use it?
5. I would recommend to put the information about ggplot, aes, etc,. before the code for visualizing the first histogram (the white one), or atleast before making a different heading for Objective 5. That way it would be easy to follow up with the codes and their information simultaneously. 
6. The most important thing that's missing is that the person following this tutorial will only be able to read the instructions/information and visualize the graphs and observe statistical tests results. However, they won't be able to achieve any goal. I encourage putting empty R code chunks in between several objectives for them to try on their own with a different hypothesis, or same hypothesis but different graphs.
7. The overall objectives are met and amazing tutorial. Good luck!

**Comment by tpymz** [comment]
Thank you for the feedback!
